//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assassins.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string user { get; set; }
        public string target { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> type { get; set; }
        public string comment { get; set; }
        public Nullable<int> gameid { get; set; }
        public string photourl { get; set; }
    }
}
